### ISSUE TITLE
Missing stylesheet?

### ISSUE THREAD

**Issue by adam-hanna** [planet-training/meteor-jquery-ui-drag-resize#1]
I could only get the resizeable feature to work by including the following in my page:

``` html
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery.ui.all.css" />
```

**Comment by dohomi** [comment]
@adam-hanna we published this package for supporting just a small set of jQuery-Ui features. It's not meant to take care of any CSS files, because we don't want it to interfere with any global app styles. I guess in a real time project and the use of jQuery-Ui you would still customize the output of all styles inside of the app, that was the reason leaving it out and only taking care of JS files.

**Comment by adam-hanna** [comment]
@dohomi makes perfect sense. I wonder why I couldn't get $('selector').resizeable () to work without the stylesheet?

**Comment by dohomi** [comment]
Because the handle is missing as far as I know - that is designed through CSS. I created this package for supporting several features for jQuery Fullcalendar, but then I figured out that the newest version of it doesn't use the jQuery-Ui any more. So currently I don't use this package, if you have anything to add please open a PR I'm happy to merge it.

**Comment by adam-hanna** [comment]
Awesome, thanks much!
