### ISSUE TITLE
resizable() doesn't work

### ISSUE THREAD

**Issue by gentunian** [planet-training/meteor-jquery-ui-drag-resize#2]
Resizable doesn't work. I removed this package and I installed:

`meteor add linto:jquery-ui`

Now the same code is working.

**Comment by dohomi** [comment]
@gentunian what is exactly not working? This package is including:

```
    'bower_components/jquery-ui/ui/core.js',
    'bower_components/jquery-ui/ui/widget.js',
    'bower_components/jquery-ui/ui/mouse.js',
    'bower_components/jquery-ui/ui/draggable.js',
    'bower_components/jquery-ui/ui/resizable.js'
```

So there shouldn't be any issue with it. `linto:jquery-ui`is the complete jquery-ui library, maybe you missed another module in your usecase?

**Comment by gentunian** [comment]
@dohomi I did a simple test by invoking `resizable()` on a JQuery object. It does not work. `draggable()` works fine, but `resizable()` is doing nothing to the object. No handles, no resize, nothing. Honestly, I don't know if another module is needed. If so, I think it should be added as dependency.

The same code works after I removed the package and installed linto package.

**Comment by dohomi** [comment]
I guess it's related to the fact that linto package is including the css as
well. Our package is only including the js, so please add your choice of
jquery-ui css and you should see the resize handle.

**Comment by gentunian** [comment]
You said that for having the resize feature I need a css? If so and the resize functionality resides in a .css I think that it should be included in your package.

**Comment by dohomi** [comment]
@gentunian we won't provide any css because it's redundant in many use cases. Beside that I haven't found a slimmed down version of the `CSS`, this package is meant to have the smallest footprint possible. 

If you going with any jQuery-UI component you will most definitely importing any kind of css framework or template. I will add a note that the `CSS`is not included, just grab your custom theme (I guess you have to do that any way) and it should work instantly.
